# A Heat environment file which can be used to enable
# Nuage backend on the compute, configured via puppet
resource_registry:
  OS::TripleO::ComputeExtraConfigPre: ../puppet/extraconfig/pre_deploy/compute/nova-nuage.yaml
  OS::TripleO::Services::ComputeNeutronCorePlugin: ../puppet/services/neutron-compute-plugin-nuage.yaml

parameter_defaults:
  NuageActiveController: '0.0.0.0'
  NuageStandbyController: '0.0.0.0'
  NovaOVSBridge: 'default_bridge'
  NovaComputeLibvirtType: 'default_type'
  NovaIPv6: False
  NuageMetadataProxySharedSecret: 'default'
  NuageNovaApiEndpoint: 'default_endpoint'
