heat_template_version: 2016-04-08

description: >
  Cisco VPFA Configuration.

parameters:

  VTSUsername:
    default: 'admin'
    description: The username for the VTS server.
    type: string
  VTSPassword:
    default: 'admin'
    type: string
    description: The password for the VTS server.
    hidden: true
  VTSServer:
    description: VTS Server IP address
    type: string
  VTSPort:
    description: Port of the VTS Server
    type: number
    default: 8888

# Temporary till we do them in tripleO
  VTSNetworkIPv4Address:
    description: IP address of the VPFA on the underlay
    type: string
    default: ''
  VTSNetworkv4Mask:
    type: string
    default: ''
  VTSNetworkIPv4Gateway:
    type: string
    default: ''

  # COMPUTE_HOST_NAME and HOSTNAME need to be derived from hiera, unless HOSTNAME is defined.
  VPFAHostname:
    description: Name of the VPFA
    type: string
    default: ''
  ComputeHostName:
    description: Name of the VPFA host
    type: string
    default: ''
  NetworkConfigMethod:
    description: Network configuration method
    type: string
    default: 'static'
  # Network IP address and Netmask need to be assigned via deployment hook
  NetworkNameServerIP:
    description: IP address of Name Server
    type: string
    default: ''
  VifType:
    description: VIF Type
    type: string
    default: 'vhostuser'

  # The interface list should come in from os-net-config
  UnderlayInterfaces:
    description: List of underlay interfaces
    type: comma_delimited_list
    default: ''
  UnderlayIpNewtorksList:
    description: List of other underlay networks reachable through the underlay interface
    type: comma_delimited_list
    default: ''

  EndpointMap:
    default: {}
    description: >
      Mapping of service endpoint -> protocol. Typically set
      via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: >
      Mapping of service_name -> network name. Typically set
      via parameter_defaults in the resource registry.  This
      mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

#Uncomment and complete if vpp resource comes to be needed
#resources:

#  Vpp:
#    type: ./vpp.yaml
#    properties:


outputs:
  role_data:
    description: Role Data for the VPFA service.
    value:
      service_name: cisco_vpfa
      config_settings:
        map_merge:
#          - get_attr: [Vpp, role_data, config_settings]
          - vts::vts_ip: {get_param: VTSServer}
            vts::vts_port: {get_param: VTSPort}
            cisco_vpfa::vpfa_hostname: {get_param: VPFAHostname}
            #cisco_vpfa::compute_hostname: {get_param: ComputeHostName}
            cisco_vpfa::vts_username: {get_param: VTSUsername}
            cisco_vpfa::vts_password: {get_param: VTSPassword}
            cisco_vpfa::net_config_method: {get_param: NetworkConfigMethod}
            cisco_vpfa::name_server: {get_param: NetworkNameServerIP}
            cisco_vpfa::under_if_list: {get_param: UnderlayInterfaces}
            cisco_vpfa::underlay_net_list: {get_param: UnderlayIpNewtorksList}
            cisco_vpfa::vpfa_ipv4_address: {get_param: VTSNetworkIPv4Address}
            cisco_vpfa::vpfa_ipv4_mask: {get_param: VTSNetworkv4Mask}
            cisco_vpfa::vts_ipv4_gateway: {get_param: VTSNetworkIPv4Gateway}

      step_config: |
        include tripleo::profile::base::cisco_vpfa
