heat_template_version: 2016-04-08

description: >
  VTS Controller Settings for Neutron ML2 Plugin.

parameters:
  VTSUsername:
    default: 'admin'
    description: The username for the VTS server.
    type: string
  VTSPassword:
    default: 'admin'
    type: string
    description: The password for the VTS server.
    hidden: true
  VTSServer:
    description: VTS Server IP address
    type: string
  VTSVMMID:
    description: VMM ID used on VTS
    type: string
    default: ''
  VTSPort:
    description: Port of the VTS Server
    type: number
    default: 8888
  VTSTimeout:
    description: Timeout for VTS server
    type: number
    default: 120
  NeutronInterfaceDriver:
  # Newton fix - TODO Remove for Queens
    description: Neutron DHCP interface driver (temporary)
    type: string
    default: 'neutron.agent.linux.interface.OVSInterfaceDriver'

  EndpointMap:
    default: {}
    description: >
      Mapping of service endpoint -> protocol. Typically set
      via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: >
      Mapping of service_name -> network name. Typically set
      via parameter_defaults in the resource registry.  This
      mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

resources:

  NeutronMl2Base:
    type: ./neutron-plugin-ml2.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the VTS ML2 Plugin.
    value:
      service_name: neutron_plugin_ml2_cisco_vts
      config_settings:
        map_merge:
          - get_attr: [NeutronMl2Base, role_data, config_settings]
          - vts::vts_ip: {get_param: VTSServer}
            vts::vts_port: {get_param: VTSPort}
            neutron::plugins::ml2::cisco::vts::vts_username: {get_param: VTSUsername}
            neutron::plugins::ml2::cisco::vts::vts_password: {get_param: VTSPassword}
            neutron::plugins::ml2::cisco::vts::vts_vmmid: {get_param: VTSVMMID}
            neutron::plugins::ml2::cisco::vts::vts_timeout: {get_param: VTSTimeout}
        # Newton fix - TODO Remove for Queens
            neutron::agents::dhcp::interface_driver: {get_param: NeutronInterfaceDriver}

      step_config: |
        include ::tripleo::profile::base::neutron::plugins::ml2
