heat_template_version: 2016-04-08

description: >
  Rsyslog client service configuration.

parameters:

  SyslogServer:
    description: The syslog server host name or IP.
    default: ''
    type: string
  ServerPort:
    description: The syslog server port.
    default: '514'
    type: string
  RemoteForwardFormat:
    description: |
      Which forward format for remote servers should be used.
    default: ''
    type: string
  LogRemote:
    description: Log Remotely
    type: boolean
    default: false
  LogLocal:
    description: Log Locally
    type: boolean
    default: false
  RemoteType:
    description: Which protocol to use when logging remotely. Valid values; tcp, udp, repl
    type: string
    default: 'tcp'
  ClientLogFilters:
    description: |
      An array of hash items defining custom logging filters using the `if/then` configurations parameter.
      E.g.  [ expression: '$programname == "foo"', action: /var/log/foo.log]
    type: comma_delimited_list
    default: |
      []
  RemoteServers:
    description: |
      String containing remote server puppet configuration hashes. See https://github.com/saz/puppet-rsyslog for format
      E.g.
       [
          {
            host => 'logs.example.org',
          },
          {
            port => '55514',
      },
      {
            host     => 'logs.somewhere.com',
            port     => '555',
            pattern  => '*.log',
            protocol => 'tcp',
            format   => 'RFC3164fmt',
          },
      ],
    type: string
    default: |
      ''

  EndpointMap:
    default: {}
    description: >
      Mapping of service endpoint -> protocol. Typically set
      via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: >
      Mapping of service_name -> network name. Typically set
      via parameter_defaults in the resource registry.  This
      mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

outputs:
  role_data:
    description: Role Data for the rsyslog client.
    value:
      service_name: rsyslog_client
      config_settings:
        map_merge:
          - rsyslog::client::server: {get_param: SyslogServer}
            rsyslog::client::port: {get_param: ServerPort}
            rsyslog::client::remote_forward_format: {get_param: RemoteForwardFormat}
            rsyslog::client::log_remote: {get_param: LogRemote}
            rsyslog::client::log_local: {get_param: LogLocal}
            rsyslog::client::remote_type: {get_param: RemoteType}
            rsyslog::client::log_filters: {get_param: ClientLogFilters }
            rsyslog::client::remote_servers: {get_param: RemoteServers}

      step_config: |
        include rsyslog::client
